### PR TITLE
Wiki Update (New and updated bdfdScripts)

### PR DESCRIPTION
**Pull request by FakuOver**
### A total of 18 new Scripts were added and data was modified in 5 Scripts...

All the information was taken from the ads on the discord server, also from the bot using the command `!commandlist $script`
Script by Script tests were also carried out to check its functionality and add good examples.

## NEW SCRIPTS
- $botCommands
- $botNode
- $channelType
- $defer
- $deleteMessage
- $getTextSplitInde
- $hostingExpireTim
- $isBanned
- $sendEmbedMessag
- $serverChannelExist
- $shardID
- $sort
- $timeout
- $trimSpac
- $unpinMessage
- $untimeout
- $url
- $userPerm

## SCRIPTS UPDATED
- $calculate
- $replaceTex
- $reply
- $mute
- $unmute

## SOURCES USED TO GET THE SCRIPTS
[Discord announced #1](https://discord.com/channels/566363823137882154/566364581522440232/895750073189826600)
[Discord announced #2](https://discord.com/channels/566363823137882154/566364581522440232/905493770286551050)
[Discord announced #3](https://discord.com/channels/566363823137882154/566364581522440232/918594902890283038)
[Discord announced #4](https://discord.com/channels/566363823137882154/566364581522440232/926893721075736669)

### CODE REVIEW

**Comment by DevSpen** [comment]
A lot of these changes conflict my local branch 😅\
I can try to pull some into there as much as possible though.

**Comment by noituri** [comment]
> A lot of these changes conflict my local branch (I know it’s been a while since a commit was made but I’m still actively working on it) 😅 I can try to incorporate some of these changes into there as much as possible though. It should be no problem to merge atm though, but we might have to resolve conflicting edits later, or something of that sorts.

I'm glad you're still working on it :)
I'm going to merge this now since I'm not sure how long it will take for your changes to be merge-ready. Later on, we'll resolve the merge conflicts if needed.

**Comment by DevSpen** [comment]
> > A lot of these changes conflict my local branch (I know it’s been a while since a commit was made but I’m still actively working on it) 😅 I can try to incorporate some of these changes into there as much as possible though. It should be no problem to merge atm though, but we might have to resolve conflicting edits later, or something of that sorts.
> 
> I'm glad you're still working on it :) I'm going to merge this now since I'm not sure how long it will take for your changes to be merge-ready. Later on, we'll resolve the merge conflicts if needed.

SGTM.

**Comment by FakuOver** [comment]
> > A lot of these changes conflict my local branch (I know it’s been a while since a commit was made but I’m still actively working on it) 😅 I can try to incorporate some of these changes into there as much as possible though. It should be no problem to merge atm though, but we might have to resolve conflicting edits later, or something of that sorts.
> 
> I'm glad you're still working on it :) I'm going to merge this now since I'm not sure how long it will take for your changes to be merge-ready. Later on, we'll resolve the merge conflicts if needed.

Uh, I'm sorry if I didn't do something right somewhere, or I forgot something.

**Comment by DevSpen** [comment]
> > > A lot of these changes conflict my local branch (I know it’s been a while since a commit was made but I’m still actively working on it) 😅 I can try to incorporate some of these changes into there as much as possible though. It should be no problem to merge atm though, but we might have to resolve conflicting edits later, or something of that sorts.
> > 
> > 
> > I'm glad you're still working on it :) I'm going to merge this now since I'm not sure how long it will take for your changes to be merge-ready. Later on, we'll resolve the merge conflicts if needed.
> 
> Uh, I'm sorry if I didn't do something right somewhere, or I forgot something.

No no, you didn’t do anything wrong!\
It is more a version control issue, on my part really, since I’m making a such a large commit at once.

**Pull request merged**
