### PR TITLE
Wiki Overhaul

### PR DESCRIPTION
**Pull request by DevSpen**
Most major changes came in: "[First refractor commit](https://github.com/NilPointer-Software/bdfd-wiki/pull/113/commits/3bde5e364dbae99b76f967fc4622f6dd26b5e524)".
When "Second refractor commit" is finished, then this PR will be mergeable

### CODE REVIEW

**Comment by DevSpen** [comment]
# Plans for Updating UI Images on Wiki
Once the update gets released to everyone (after the iOS update), then I will start full conversion of wiki's images to the new UI.
Any of the new images in the wiki are of the new UI.

**Comment by noituri** [comment]
That's awesome. Thanks

**Comment by MineBartekSA** [comment]
We are in process of rewriting how we handle arguments, so there will be changes to how they are displayed.

For now, you can expect:
- Optional arguments will be displayed in (), e.g. 
  `$startThread[name;chanenl ID;message ID;(archive duration;return thread/channel ID)]`
- Tuple arguments (arguments that must be together), will be displayed in <>, e.g.
  `$awaitReactions[<command name;reaction>;...]` (in this example you can repeat two arguments)
- Ellipsis, the `...`, now will be displayed in every command that uses it
- Arguments now will have their own description if there is a need for it
- All arguments will have a definite type
- Some arguments will be flagged with `Can be empty` flag

The Help tab in the app will be getting a bit more of an overhaul to display this info.
I'll also be updating the `!commandlist` Master Bot command to let it display all this new argument info.

Also, suggestions for argument descriptions will be appreciated.

**Comment by DevSpen** [comment]
> We are in process of rewriting how we handle arguments, so there will be changes to how they are displayed.
> 
> For now, you can expect:
> 
> * Optional arguments will be displayed in (), e.g.
>   `$startThread[name;chanenl ID;message ID;(archive duration;return thread/channel ID)]`
> * Tuple arguments (arguments that must be together), will be displayed in <>, e.g.
>   `$awaitReactions[<command name;reaction>;...]` (in this example you can repeat two arguments)
> * Ellipsis, the `...`, now will be displayed in every command that uses it
> * Arguments now will have their own description if there is a need for it
> * All arguments will have a definite type
> * Some arguments will be flagged with `Can be empty` flag
> 
> The Help tab in the app will be getting a bit more of an overhaul to display this info. I'll also be updating the `!commandlist` Master Bot command to let it display all this new argument info.
> 
> Also, suggestions for argument descriptions will be appreciated.
> 
> This is just a heads-up because these changes are still being worked on. They won't be released any time soon. (but we want to release them as soon as possible)

Thanks for the info, I'll be sure to open another PR optimizing the wiki for the new argument syntax, once those changes become more imminent!

**Comment by DevSpen** [comment]
For a quick timeline, this will be finished before 2022.\
I will continue to work on it during my weeks off for the holidays.\
But next week, I will be unavailable from Thursday-Sunday.

**Comment by noituri** [comment]
> For a quick timeline, this will be finished before 2022. I will continue to work on it during my weeks off for the holidays. But next week, I will be unavailable from Thursday-Sunday.

Thanks <3

**Comment by DevSpen** [comment]
#117, this will be added here along with other missing functions, if someone wants to PR it before this get merged, I’ll use that version

**Comment by FakuOver** [comment]
> # Planes para actualizar las imágenes de la interfaz de usuario en Wiki
> Una vez que la actualización se publique para todos (después de la actualización de iOS), comenzaré la conversión completa de las imágenes de wiki a la nueva interfaz de usuario. Cualquiera de las nuevas imágenes en el wiki son de la nueva interfaz de usuario, a partir de este PR.

If the images have not been updated yet, I have no problems updating everything, or well, most of them. 😅

**Comment by DevSpen** [comment]
> > # Planes para actualizar las imágenes de la interfaz de usuario en Wiki
> > Una vez que la actualización se publique para todos (después de la actualización de iOS), comenzaré la conversión completa de las imágenes de wiki a la nueva interfaz de usuario. Cualquiera de las nuevas imágenes en el wiki son de la nueva interfaz de usuario, a partir de este PR.
> 
> If the images have not been updated yet, I have no problems updating everything, or well, most of them. 😅

We're waiting on the iOS update for now, hopefully that’s soon 👀

**Comment by DodoGames7** [comment]
Great to hear

**Comment by DevSpen** [comment]
This PR is stale, I still have these changes locally and will make a new PR soon.

**Pull request closed without merging**
