### PR TITLE
Update 9

### PR DESCRIPTION
**Pull request by Rainb0wKey**
Updated reply design for 4 themes:
- `iOS`
- `Green`
- `Bot Designer For Discord`
- `Light`

### CODE REVIEW

**Comment by Rainb0wKey** [comment]
iosTheme

**Comment by Rainb0wKey** [comment]
I need a little more time to update the quotes!

**Comment by Rainb0wKey** [comment]
> Contributor

Updated!!!

**Review by MineBartekSA — APPROVED** [review]
Thank you for your contribution

**Pull request merged**
