### PR TITLE
Updated $removeButtons

### PR DESCRIPTION
**Pull request by xNickyDev**

### CODE REVIEW

**Comment by xNickyDev** [comment]
Idk why the other commits are still shown

**Comment by Kitosight** [comment]
> Idk why the other commits are still shown

Basically don't use the same branch. Do changes in the new ones but first create it from our `dev` branch.

image

If you're working from VS Code, I can show the new example.

**Comment by xNickyDev** [comment]
> 

Alright, but does it matter what name the branch has or can I decide that by myself?

**Comment by Kitosight** [comment]
> > 
> 
> Alright, but does it matter what name the branch has or can I decide that by myself?

Actually whatever you want. Personally, I name it with the day the branch was created (aka when I started working on the new wiki update).

**Comment by xNickyDev** [comment]
> Actually whatever you want. Personally, I name it with the day the branch was created (aka when I started working on the new wiki update).

Okay thanks! So should I create a new pull request (with the new branch I created) and close this one? Or aren't the older commits a big problem and just look messy?

**Review by MineBartekSA — CHANGES_REQUESTED** [review]
Please add simple examples.

And to answer your question, the older commits aren't a problem. This PR will just look messy.

**Comment by xNickyDev** [comment]
> Please add simple examples.
> 
> And to answer your question, the older commits aren't a problem. This PR will just look messy.

Alright 👍

**Review by MineBartekSA — APPROVED** [review]
Thank you for your contribution

**Pull request merged**
